### ISSUE TITLE
conflicting license information in readme

### ISSUE THREAD

**Issue by danmarsden** [skynettechnologies/moodle-local_allinoneaccessibility#1]
Moodle plugins are GPL - (and the php comments in your code include the header) but your readme states the plugin is licensed under MIT:
https://github.com/skynettechnologies/moodle-allinoneaccessibility/blob/main/README.md#license

**Comment by danmarsden** [comment]
https://github.com/skynettechnologies/moodle-allinoneaccessibility/blob/main/LICENSE is also incorrect - it should have the GPL license in there.

This is a blocker for plugins db approval.

**Comment by skynetindia** [comment]
We have updated the license to GPL in the readme and license file.
