### ISSUE TITLE
missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [skynettechnologies/moodle-local_allinoneaccessibility#3]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. Your plugin integrates with an external service so the privacy api must be implemented prior to approval in the plugins db. In particular you need to look closely at the external link location part that may need to be implemented by your plugin:
https://moodledev.io/docs/apis/subsystems/privacy#indicating-that-you-export-data-to-an-external-location

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://moodledev.io/docs/apis/subsystems/privacy

**Comment by danmarsden** [comment]
looks like this is still missing - as mentioned above. this is a blocker for plugins db approval as your plugin integrates with an external service.

**Comment by skynetindia** [comment]
We have implemented the privacy api. Please check the same and give us feedback.
