### ISSUE TITLE
invalid lang file.

### ISSUE THREAD

**Issue by danmarsden** [skynettechnologies/moodle-local_allinoneaccessibility#4]
The lang pack files are supposed to be simple strings, it is not a place to store javascript or to have other php executable code.

string concatentaion in the lang packs is also not allowed - it causes problems for the Moodle translation tool

eg:
$string['test'] = "sometext"."somemoretext";
or
$string['test'] = "sometext".$string['someotheritem'];

each line in the file should be a simple string  contained within one set of quotes eg:
$string['test'] = "sometext somemoretext"; 

This is a blocker for plugins db approval.

**Comment by skynetindia** [comment]
We have made it a language file with only simple strings.
