### ISSUE TITLE
moodle.org plugins db entry description needs improving

### ISSUE THREAD

**Issue by danmarsden** [skynettechnologies/moodle-local_allinoneaccessibility#6]
The plugins db entry doesn't say much about what this plugin does and "how" it does it - it also doesn't mention any details about the commercial aspects of the plugin - what features are provided for free/ what features need to be paid for - please improve the plugins db entry to make this a lot clearer.

note this is a blocker for plugins db approval.

**Comment by skynetindia** [comment]
We have mention the list of all features(paid/free)
