### ISSUE TITLE
camel case used in strings.

### ISSUE THREAD

**Issue by danmarsden** [skynettechnologies/moodle-local_allinoneaccessibility#7]
Moodle uses sentence case - please check your lang strings as some use camel case.

for example strings like:
$string['mystring'] = "My String";
should be:
$string['mystring'] = "My string";

Note: this is not a blocker for approval in the plugins db.

**Comment by skynetindia** [comment]
We have updated the lang strings.

**Comment by danmarsden** [comment]
did you push your updates?

I still many examples like:
$string['aioa-top_center'] = 'Top Center';
$string['aioa-top_right'] = 'Top Right';

which should be:
$string['aioa-top_center'] = 'Top center';
$string['aioa-top_right'] = 'Top right';
