### ISSUE TITLE
Not enough information in the moodle.org plugins db description that describes the commercial aspects of the plugin

### ISSUE THREAD

**Issue by danmarsden** [skynettechnologies/moodle-local_allinoneaccessibility#9]
in your plugins db entry you need to clearly state that your plugin requires a commercial subscription to use the main features - if there are some features available for free, it should be clear what those features are within the description.

to edit that description, please go to the developer zone tab and hit the "edit this plugin" down the bottom.

note this is a blocker for plugins db approval.

**Comment by skynetindia** [comment]
We have described the list of available features (paid/free)
